# Generated by Django 6.0 on 2025-12-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration_minutes', models.PositiveSmallIntegerField()),
                ('release_date', models.DateField()),
                ('rating', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
